name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dependency-scan:
    name: Dependency Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency Review (GitHub built-in)
        uses: actions/dependency-review-action@v3

      - name: Python Dependency Audit
        uses: pypa/gh-action-pip-audit@v1.0.8

      - name: Node.js Audit
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm install
            npm audit --audit-level=high
          else
            echo "No Node.js dependencies found."
          fi

  docker-scan:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.11.0
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          ignore-unfixed: true

  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true
