name: Security Scan

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Weekly run

jobs:
  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          export SETUPTOOLS_USE_DISTUTILS=stdlib
          pip3 install safety pytest

      - name: Run Safety (Python dependency scanning)
        run: safety check --full-report || true

      - name: Run tests (skip broken URL checks)
        run: pytest -s -k "not test_url" || true
